services:
    app.admin.head_block:
        class: AppBundle\Admin\HeadBlockAdmin
        arguments: [~, AppBundle\Entity\HeadBlock, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Контент, label: Шапка}
